name = "geodiametrics-aggregator"
main = "src/index.js"
compatibility_date = "2026-01-31"

[durable_objects]
bindings = [
  { name = "METRICS_DO", class_name = "MetricsDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["MetricsDO"]
